name: Build/push Container
on: []
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file=Dockerfile --tag=ghcr.io/phargogh/nci-assert-values-greater-than-baseline --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to registry
        run: docker push ghcr.io/phargogh/nci-assert-values-greater-than-baseline
